### ISSUE TITLE
Go!プリンセスプリキュアの実装

### ISSUE THREAD

**Issue by ligun** [ligun/groovycure#5]
キュアフローラ
キュアマーメイド
キュアトゥインクル

**Comment by sue445** [comment]
FYI https://github.com/sue445/rubicure/pull/66

**Comment by ligun** [comment]
おぉ、すでにとりかかってるんですね！
(GitHubってこんなに高機能だったんだｗ)

ありがとうございます！

**Comment by ligun** [comment]
@d2c29001905f5b52c5524815d6ce26da2e0f0715

**Comment by ligun** [comment]
@9975eaed7192b7941ac056c839334b846dc812d1
